# Generated by Django 6.0.2 on 2026-02-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('one_time', 'Única Vez')], default='weekly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de Checklist',
                'verbose_name_plural': 'Templates de Checklists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Início do Período')),
                ('period_end', models.DateField(verbose_name='Fim do Período')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.site')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição / Instrução')),
                ('category', models.CharField(choices=[('analytics', 'Analytics'), ('seo', 'SEO'), ('content', 'Conteúdo'), ('technical', 'Técnico'), ('social', 'Social Media'), ('reporting', 'Relatórios')], default='seo', max_length=20)),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('tool_hint', models.CharField(blank=True, help_text='Ex: GA4, GSC, Ahrefs, RankPulse', max_length=200, verbose_name='Ferramenta')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Item do Template',
                'verbose_name_plural': 'Items do Template',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistCompletedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_items', to='checklists.checklistinstance')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.checklisttemplateitem')),
            ],
            options={
                'verbose_name': 'Item Completado',
                'verbose_name_plural': 'Items Completados',
                'unique_together': {('instance', 'template_item')},
            },
        ),
    ]
