# Generated by Django 6.0.2 on 2026-02-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Cluster')),
                ('pillar_keyword', models.CharField(max_length=300, verbose_name='Keyword Pilar')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_clusters', to='core.site')),
            ],
            options={
                'verbose_name': 'Cluster de Conteúdo',
                'verbose_name_plural': 'Clusters de Conteúdo',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('target_keyword', models.CharField(max_length=300, verbose_name='Keyword Alvo')),
                ('content_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('landing_page', 'Landing Page'), ('faq', 'FAQ'), ('guide', 'Guia Completo'), ('comparison', 'Comparativo'), ('case_study', 'Case Study')], default='blog_post', max_length=20)),
                ('status', models.CharField(choices=[('idea', 'Ideia'), ('planned', 'Planejado'), ('generating', 'Gerando'), ('review', 'Em Revisão'), ('published', 'Publicado')], default='idea', max_length=20)),
                ('search_volume', models.IntegerField(default=0, verbose_name='Volume de Busca')),
                ('difficulty', models.IntegerField(default=0, verbose_name='Dificuldade (0-100)')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridade (1-10)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.contentcluster')),
            ],
            options={
                'verbose_name': 'Tópico de Conteúdo',
                'verbose_name_plural': 'Tópicos de Conteúdo',
                'ordering': ['-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título Gerado')),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('content_html', models.TextField(verbose_name='Conteúdo HTML')),
                ('content_markdown', models.TextField(blank=True, verbose_name='Conteúdo Markdown')),
                ('word_count', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=50, verbose_name='Modelo IA')),
                ('prompt_used', models.TextField(blank=True, verbose_name='Prompt Utilizado')),
                ('tokens_used', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('published_url', models.URLField(blank=True, verbose_name='URL Publicada')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_posts', to='content.contenttopic')),
            ],
            options={
                'verbose_name': 'Post Gerado',
                'verbose_name_plural': 'Posts Gerados',
                'ordering': ['-created_at'],
            },
        ),
    ]
