# Generated by Django 6.0.3 on 2026-03-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0014_aiprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram_feed', 'Instagram Feed'), ('instagram_stories', 'Instagram Stories'), ('instagram_reels', 'Instagram Reels'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em Revisão'), ('approved', 'Aprovado'), ('scheduled', 'Agendado'), ('published', 'Publicado'), ('rejected', 'Rejeitado')], default='draft', max_length=20)),
                ('theme', models.CharField(max_length=300, verbose_name='Tema / Assunto')),
                ('caption', models.TextField(verbose_name='Legenda / Copy')),
                ('hashtags', models.TextField(blank=True, verbose_name='Hashtags')),
                ('cta', models.CharField(blank=True, max_length=300, verbose_name='Call-to-Action')),
                ('image_prompt', models.TextField(blank=True, verbose_name='Prompt da Imagem')),
                ('image_url', models.URLField(blank=True, verbose_name='URL da Imagem Gerada')),
                ('image_file', models.ImageField(blank=True, upload_to='social_images/')),
                ('model_used', models.CharField(blank=True, max_length=80)),
                ('generation_params', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='core.project')),
            ],
            options={
                'verbose_name': 'Post Social',
                'verbose_name_plural': 'Posts Sociais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='core.project')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries', to='content.socialpost')),
            ],
            options={
                'verbose_name': 'Entrada Calendário',
                'verbose_name_plural': 'Calendário de Conteúdo',
                'ordering': ['date', 'time_slot'],
            },
        ),
    ]
