# Generated by Django 6.0.2 on 2026-02-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Site')),
                ('domain', models.CharField(max_length=253, unique=True, verbose_name='Domínio')),
                ('url', models.URLField(verbose_name='URL Base')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('ga4_measurement_id', models.CharField(blank=True, help_text='Ex: G-BCGGTGQJR9', max_length=30, verbose_name='GA4 Measurement ID')),
                ('ga4_api_secret', models.CharField(blank=True, help_text='Measurement Protocol API secret', max_length=100, verbose_name='GA4 API Secret')),
                ('ga4_property_id', models.CharField(blank=True, help_text='Para GA4 Data API (reporting)', max_length=30, verbose_name='GA4 Property ID')),
                ('gsc_verified', models.BooleanField(default=False, verbose_name='GSC Verificado')),
                ('gsc_site_url', models.URLField(blank=True, verbose_name='GSC Site URL')),
                ('sitemap_url', models.URLField(blank=True, verbose_name='Sitemap URL')),
                ('robots_txt_url', models.URLField(blank=True, verbose_name='robots.txt URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KPIGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='Ex: Sessões Orgânicas, Sign-ups, Receita Orgânica', max_length=200, verbose_name='Nome da Métrica')),
                ('source', models.CharField(help_text='Ex: GA4, GSC, Admin', max_length=100, verbose_name='Fonte')),
                ('period', models.CharField(choices=[('month_1', 'Mês 1'), ('month_3', 'Mês 3'), ('month_6', 'Mês 6'), ('month_12', 'Mês 12')], max_length=10)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Atual')),
                ('unit', models.CharField(blank=True, default='', help_text='Ex: R$, %, unidades', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_goals', to='core.site')),
            ],
            options={
                'verbose_name': 'Meta de KPI',
                'verbose_name_plural': 'Metas de KPI',
                'ordering': ['site', 'period', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='GA4EventDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Ex: sign_up, generate_lead, purchase', max_length=100, verbose_name='Nome do Evento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('trigger_page', models.CharField(blank=True, help_text='Template ou URL onde o evento deve ser disparado', max_length=500, verbose_name='Página de Disparo')),
                ('priority', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='medium', max_length=10)),
                ('js_snippet', models.TextField(blank=True, help_text='Snippet gtag() para copiar no template', verbose_name='Código JavaScript')),
                ('server_side', models.BooleanField(default=False, verbose_name='Server-Side (Measurement Protocol)')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parâmetros padrão do evento em JSON', verbose_name='Parâmetros')),
                ('is_conversion', models.BooleanField(default=False, verbose_name='É evento de conversão (Key Event)')),
                ('is_implemented', models.BooleanField(default=False, verbose_name='Implementado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_definitions', to='core.site')),
            ],
            options={
                'verbose_name': 'Definição de Evento GA4',
                'verbose_name_plural': 'Definições de Eventos GA4',
                'ordering': ['site', 'priority', 'event_name'],
                'unique_together': {('site', 'event_name')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Início da Semana')),
                ('week_end', models.DateField(verbose_name='Fim da Semana')),
                ('organic_sessions', models.IntegerField(default=0, verbose_name='Sessões Orgânicas')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='Sessões Totais')),
                ('signups', models.IntegerField(default=0, verbose_name='Sign-ups')),
                ('purchases', models.IntegerField(default=0, verbose_name='Compras')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita (R$)')),
                ('gsc_impressions', models.IntegerField(default=0, verbose_name='Impressões GSC')),
                ('gsc_clicks', models.IntegerField(default=0, verbose_name='Cliques GSC')),
                ('gsc_ctr', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CTR (%)')),
                ('gsc_position', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Posição Média')),
                ('keywords_top10', models.IntegerField(default=0, verbose_name='Keywords Top 10')),
                ('posts_published', models.IntegerField(default=0, verbose_name='Posts Publicados')),
                ('backlinks', models.IntegerField(default=0, verbose_name='Backlinks')),
                ('highlights', models.TextField(blank=True, verbose_name='Destaques')),
                ('issues', models.TextField(blank=True, verbose_name='Problemas')),
                ('next_steps', models.TextField(blank=True, verbose_name='Próximos Passos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_snapshots', to='core.site')),
            ],
            options={
                'verbose_name': 'Snapshot Semanal',
                'verbose_name_plural': 'Snapshots Semanais',
                'ordering': ['-week_start'],
                'unique_together': {('site', 'week_start')},
            },
        ),
    ]
