# Generated by Django 6.0.3 on 2026-03-07 04:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_site_google_oauth_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='google_ads_client_id',
        ),
        migrations.RemoveField(
            model_name='site',
            name='google_ads_client_secret',
        ),
        migrations.RemoveField(
            model_name='site',
            name='google_ads_customer_id',
        ),
        migrations.RemoveField(
            model_name='site',
            name='google_ads_developer_token',
        ),
        migrations.RemoveField(
            model_name='site',
            name='google_ads_login_customer_id',
        ),
        migrations.RemoveField(
            model_name='site',
            name='google_ads_refresh_token',
        ),
        migrations.RemoveField(
            model_name='site',
            name='owner',
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Alerta')),
                ('metric', models.CharField(choices=[('sessions', 'Sessões Orgânicas'), ('gsc_clicks', 'Cliques GSC'), ('gsc_impressions', 'Impressões GSC'), ('gsc_position', 'Posição Média GSC'), ('ads_spend', 'Gasto Google Ads'), ('ads_clicks', 'Cliques Google Ads'), ('ads_cpc', 'CPC Google Ads'), ('ads_conversions', 'Conversões Google Ads'), ('meta_spend', 'Gasto Meta Ads'), ('meta_clicks', 'Cliques Meta Ads'), ('meta_cpc', 'CPC Meta Ads')], max_length=30, verbose_name='Métrica')),
                ('condition', models.CharField(choices=[('gt', 'Maior que'), ('lt', 'Menor que'), ('change_up', 'Subiu mais que (%)'), ('change_down', 'Caiu mais que (%)')], max_length=20, verbose_name='Condição')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Valor absoluto ou percentual conforme condição', max_digits=12, verbose_name='Limite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notify_email', models.BooleanField(default=False, verbose_name='Notificar por Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Regra de Alerta',
                'verbose_name_plural': 'Regras de Alerta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Aviso'), ('critical', 'Crítico')], default='warning', max_length=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Atual')),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Anterior')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lido')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.alertrule', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Evento de Alerta',
                'verbose_name_plural': 'Eventos de Alerta',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Em Execução'), ('done', 'Concluído'), ('error', 'Erro')], default='running', max_length=10)),
                ('business_summary', models.TextField(blank=True, verbose_name='Resumo do Negócio')),
                ('overall_score', models.IntegerField(blank=True, null=True, verbose_name='Score Geral (0-100)')),
                ('overall_analysis', models.TextField(blank=True, verbose_name='Análise Geral')),
                ('raw_data_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot dos Dados')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_reports', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Relatório de Auditoria IA',
                'verbose_name_plural': 'Relatórios de Auditoria IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads'), ('seo', 'SEO / GSC'), ('general', 'Geral')], max_length=20)),
                ('category', models.CharField(choices=[('negative_keywords', 'Palavras-Chave Negativas'), ('sitelinks', 'Sitelinks'), ('callouts', 'Callouts / Extensões'), ('ad_copy', 'Texto do Anúncio'), ('bidding', 'Estratégia de Lances'), ('targeting', 'Segmentação de Público'), ('audience_age', 'Faixa Etária'), ('audience_interests', 'Interesses'), ('audience_geo', 'Geolocalização'), ('ad_schedule', 'Agendamento'), ('keywords', 'Palavras-Chave'), ('quality_score', 'Quality Score'), ('campaign_structure', 'Estrutura de Campanha'), ('creative', 'Criativos'), ('landing_page', 'Landing Page'), ('conversion_tracking', 'Rastreamento de Conversão'), ('indexing', 'Indexação'), ('content_gap', 'Gap de Conteúdo'), ('other', 'Outro')], default='other', max_length=30)),
                ('impact', models.CharField(choices=[('critical', 'Crítico'), ('high', 'Alto'), ('medium', 'Médio'), ('low', 'Baixo')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('explanation', models.TextField(verbose_name='Explicação Detalhada')),
                ('action_description', models.TextField(blank=True, verbose_name='Ação Proposta')),
                ('action_payload', models.JSONField(blank=True, default=dict, help_text='Dados estruturados para execução automática', verbose_name='Payload da Ação')),
                ('can_auto_apply', models.BooleanField(default=False, verbose_name='Aplicável Automaticamente')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('applied', 'Aplicado'), ('dismissed', 'Descartado'), ('failed', 'Falhou')], default='pending', max_length=10)),
                ('apply_result', models.JSONField(blank=True, default=dict, verbose_name='Resultado da Aplicação')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Campanha')),
                ('campaign_name', models.CharField(blank=True, max_length=300, verbose_name='Nome da Campanha')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.auditreport', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Recomendação de Auditoria',
                'verbose_name_plural': 'Recomendações de Auditoria',
                'ordering': ['report', 'impact', 'platform'],
            },
        ),
    ]
