# Generated by Django 6.0.2 on 2026-03-07 03:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_site_google_ads_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Alerta')),
                ('metric', models.CharField(choices=[('sessions', 'Sessões Orgânicas'), ('gsc_clicks', 'Cliques GSC'), ('gsc_impressions', 'Impressões GSC'), ('gsc_position', 'Posição Média GSC'), ('ads_spend', 'Gasto Google Ads'), ('ads_clicks', 'Cliques Google Ads'), ('ads_cpc', 'CPC Google Ads'), ('ads_conversions', 'Conversões Google Ads'), ('meta_spend', 'Gasto Meta Ads'), ('meta_clicks', 'Cliques Meta Ads'), ('meta_cpc', 'CPC Meta Ads')], max_length=30, verbose_name='Métrica')),
                ('condition', models.CharField(choices=[('gt', 'Maior que'), ('lt', 'Menor que'), ('change_up', 'Subiu mais que (%)'), ('change_down', 'Caiu mais que (%)')], max_length=20, verbose_name='Condição')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Valor absoluto ou percentual conforme condição', max_digits=12, verbose_name='Limite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notify_email', models.BooleanField(default=False, verbose_name='Notificar por Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Regra de Alerta',
                'verbose_name_plural': 'Regras de Alerta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Aviso'), ('critical', 'Crítico')], default='warning', max_length=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Atual')),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Anterior')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lido')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.alertrule', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Evento de Alerta',
                'verbose_name_plural': 'Eventos de Alerta',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
