# Generated by Django 6.0.3 on 2026-03-07 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditreport_auditrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreport',
            name='progress_step',
            field=models.CharField(blank=True, help_text='Etapa atual do processamento assíncrono', max_length=50, verbose_name='Etapa Atual'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_goals',
            field=models.TextField(blank=True, help_text='Ex: Gerar leads, vendas online, brand awareness, agendamentos', verbose_name='Objetivos do Negócio'),
        ),
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_content', models.TextField(blank=True, help_text='Seções extraídas: serviços, sobre, preços, depoimentos', verbose_name='Conteúdo Estruturado do Site')),
                ('website_raw_text', models.TextField(blank=True, verbose_name='Texto Bruto do Site')),
                ('instagram_profile', models.JSONField(blank=True, default=dict, help_text='username, bio, followers, media_count, profile_pic_url', verbose_name='Perfil Instagram')),
                ('instagram_posts', models.JSONField(blank=True, default=list, help_text='Últimos 25 posts com caption, engagement, media_type', verbose_name='Posts Instagram')),
                ('facebook_page', models.JSONField(blank=True, default=dict, help_text='name, about, fan_count, category, website', verbose_name='Página Facebook')),
                ('facebook_posts', models.JSONField(blank=True, default=list, help_text='Últimos 25 posts com message, reactions, shares', verbose_name='Posts Facebook')),
                ('brand_summary', models.TextField(blank=True, help_text='Resumo completo da marca gerado pela IA', verbose_name='Brand DNA (resumo IA)')),
                ('target_audience', models.TextField(blank=True, verbose_name='Público-Alvo Inferido')),
                ('tone_of_voice', models.CharField(blank=True, help_text='Ex: formal, informal, técnico, jovem, premium', max_length=100, verbose_name='Tom de Voz')),
                ('key_services', models.JSONField(blank=True, default=list, help_text='Lista de serviços ou produtos identificados', verbose_name='Serviços/Produtos')),
                ('differentiators', models.TextField(blank=True, verbose_name='Diferenciais Competitivos')),
                ('last_website_scan', models.DateTimeField(blank=True, null=True)),
                ('last_social_scan', models.DateTimeField(blank=True, null=True)),
                ('last_brand_analysis', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Perfil da Marca',
                'verbose_name_plural': 'Perfis de Marca',
            },
        ),
        migrations.CreateModel(
            name='DataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('meta_campaigns', 'Meta Ads — Campanhas'), ('meta_ad_sets', 'Meta Ads — Conjuntos de Anúncios'), ('meta_ads_creatives', 'Meta Ads — Anúncios/Criativos'), ('meta_demographics', 'Meta Ads — Demografia'), ('meta_placements', 'Meta Ads — Posicionamentos'), ('meta_ad_insights', 'Meta Ads — Insights por Anúncio'), ('meta_account_overview', 'Meta Ads — Visão Geral da Conta'), ('meta_campaign_insights', 'Meta Ads — Insights por Campanha'), ('google_campaigns', 'Google Ads — Campanhas'), ('google_campaign_details', 'Google Ads — Detalhes de Campanhas'), ('google_keywords', 'Google Ads — Palavras-Chave'), ('google_search_terms', 'Google Ads — Termos de Busca'), ('google_ad_copies', 'Google Ads — Textos dos Anúncios'), ('google_assets', 'Google Ads — Extensões'), ('google_locations', 'Google Ads — Localização'), ('google_ad_groups', 'Google Ads — Grupos de Anúncios'), ('google_performance', 'Google Ads — Performance 30d'), ('seo_queries', 'SEO — Queries'), ('seo_pages', 'SEO — Páginas'), ('seo_daily', 'SEO — Totais Diários')], max_length=30, verbose_name='Tipo de Dado')),
                ('data', models.JSONField(default=list, verbose_name='Dados Completos')),
                ('record_count', models.IntegerField(default=0, verbose_name='Registros')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Válido')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_snapshots', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Snapshot de Dados',
                'verbose_name_plural': 'Snapshots de Dados',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['project', 'data_type', '-collected_at'], name='core_datasn_project_2db448_idx')],
            },
        ),
    ]
