# Generated by Django 6.0.3 on 2026-03-07 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ga4_datatypes_auditconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecommendation',
            name='verification_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='Resultado da Verificação'),
        ),
        migrations.AddField(
            model_name='auditrecommendation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verificado em'),
        ),
        migrations.AlterField(
            model_name='datasnapshot',
            name='data_type',
            field=models.CharField(choices=[('meta_campaigns', 'Meta Ads — Campanhas'), ('meta_ad_sets', 'Meta Ads — Conjuntos de Anúncios'), ('meta_ads_creatives', 'Meta Ads — Anúncios/Criativos'), ('meta_demographics', 'Meta Ads — Demografia'), ('meta_placements', 'Meta Ads — Posicionamentos'), ('meta_ad_insights', 'Meta Ads — Insights por Anúncio'), ('meta_account_overview', 'Meta Ads — Visão Geral da Conta'), ('meta_campaign_insights', 'Meta Ads — Insights por Campanha'), ('google_campaigns', 'Google Ads — Campanhas'), ('google_campaign_details', 'Google Ads — Detalhes de Campanhas'), ('google_keywords', 'Google Ads — Palavras-Chave'), ('google_search_terms', 'Google Ads — Termos de Busca'), ('google_ad_copies', 'Google Ads — Textos dos Anúncios'), ('google_assets', 'Google Ads — Extensões'), ('google_locations', 'Google Ads — Localização'), ('google_ad_groups', 'Google Ads — Grupos de Anúncios'), ('google_performance', 'Google Ads — Performance 30d'), ('seo_queries', 'SEO — Queries'), ('seo_pages', 'SEO — Páginas'), ('seo_daily', 'SEO — Totais Diários'), ('ga4_overview', 'GA4 — Visão Geral'), ('ga4_traffic_sources', 'GA4 — Fontes de Tráfego'), ('ga4_top_pages', 'GA4 — Top Páginas'), ('ga4_organic_traffic', 'GA4 — Tráfego Orgânico'), ('ga4_conversions', 'GA4 — Conversões'), ('ga4_demographics', 'GA4 — Demografia'), ('ga4_devices', 'GA4 — Dispositivos')], max_length=30, verbose_name='Tipo de Dado'),
        ),
        migrations.CreateModel(
            name='ProjectLearningContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compiled_prompt', models.TextField(blank=True, help_text='Contexto enviado à IA em cada auditoria — editável pelo usuário', verbose_name='Prompt Compilado')),
                ('general_guidelines', models.TextField(blank=True, help_text='Regras e preferências do usuário em texto livre', verbose_name='Orientações Gerais')),
                ('auto_summary', models.TextField(blank=True, help_text='Resumo gerado pela IA a partir das observações acumuladas', verbose_name='Resumo Automático')),
                ('last_compiled_at', models.DateTimeField(blank=True, null=True)),
                ('notes_count_at_compile', models.IntegerField(default=0, verbose_name='Notas no último compile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_context', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Contexto de Aprendizado',
                'verbose_name_plural': 'Contextos de Aprendizado',
            },
        ),
        migrations.CreateModel(
            name='RecommendationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.auditrecommendation', verbose_name='Recomendação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_notes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Observação de Recomendação',
                'verbose_name_plural': 'Observações de Recomendações',
                'ordering': ['created_at'],
            },
        ),
    ]
