# Generated by Django 6.0.2 on 2026-03-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ga4_datatypes_auditconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasnapshot',
            name='data_type',
            field=models.CharField(choices=[('meta_campaigns', 'Meta Ads — Campanhas'), ('meta_ad_sets', 'Meta Ads — Conjuntos de Anúncios'), ('meta_ads_creatives', 'Meta Ads — Anúncios/Criativos'), ('meta_demographics', 'Meta Ads — Demografia'), ('meta_placements', 'Meta Ads — Posicionamentos'), ('meta_ad_insights', 'Meta Ads — Insights por Anúncio'), ('meta_account_overview', 'Meta Ads — Visão Geral da Conta'), ('meta_campaign_insights', 'Meta Ads — Insights por Campanha'), ('google_campaigns', 'Google Ads — Campanhas'), ('google_campaign_details', 'Google Ads — Detalhes de Campanhas'), ('google_keywords', 'Google Ads — Palavras-Chave'), ('google_search_terms', 'Google Ads — Termos de Busca'), ('google_ad_copies', 'Google Ads — Textos dos Anúncios'), ('google_assets', 'Google Ads — Extensões'), ('google_locations', 'Google Ads — Localização'), ('google_ad_groups', 'Google Ads — Grupos de Anúncios'), ('google_performance', 'Google Ads — Performance 30d'), ('seo_queries', 'SEO — Queries'), ('seo_pages', 'SEO — Páginas'), ('seo_daily', 'SEO — Totais Diários'), ('ga4_overview', 'GA4 — Visão Geral'), ('ga4_traffic_sources', 'GA4 — Fontes de Tráfego'), ('ga4_top_pages', 'GA4 — Top Páginas'), ('ga4_organic_traffic', 'GA4 — Tráfego Orgânico'), ('ga4_conversions', 'GA4 — Conversões'), ('ga4_demographics', 'GA4 — Demografia'), ('ga4_devices', 'GA4 — Dispositivos')], max_length=30, verbose_name='Tipo de Dado'),
        ),
    ]
