# Generated by Django 6.0.2 on 2026-03-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_datasnapshot_data_type'),
        ('core', '0010_learning_loop_notes_verify'),
    ]

    operations = [
    ]
