# Generated by Django 6.0.3 on 2026-03-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260307_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecommendation',
            name='estimated_points',
            field=models.IntegerField(default=0, help_text='Pontos que o usuário ganha ao aplicar esta recomendação', verbose_name='Pontos Estimados'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='discovered_urls',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs do site descobertas via crawling', verbose_name='URLs Descobertas'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='total_pages_found',
            field=models.IntegerField(default=0, verbose_name='Total de Páginas'),
        ),
    ]
