# Generated by Django 6.0.3 on 2026-03-08 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_expert_article_project_score_estimated_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('source_url', models.URLField(blank=True, verbose_name='URL de Origem')),
                ('category', models.CharField(choices=[('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads'), ('seo', 'SEO'), ('analytics', 'Analytics / GA4'), ('landing_page', 'Landing Pages'), ('copywriting', 'Copywriting Publicitário'), ('conversion', 'Otimização de Conversão'), ('general', 'Marketing Digital Geral')], default='general', max_length=20)),
                ('content', models.TextField(help_text='Texto completo do artigo / conhecimento especialista', verbose_name='Conteúdo')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='Chunks Embeddados')),
                ('embedded_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Embedding')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Artigo Especialista',
                'verbose_name_plural': 'Artigos Especialistas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0, verbose_name='Score Geral (0-100)')),
                ('audit_score', models.IntegerField(default=0, verbose_name='Score Auditoria')),
                ('pending_points', models.IntegerField(default=0, verbose_name='Pontos Pendentes')),
                ('earned_points', models.IntegerField(default=0, verbose_name='Pontos Conquistados')),
                ('total_possible', models.IntegerField(default=0, verbose_name='Total Possível')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Score do Projeto',
                'verbose_name_plural': 'Scores dos Projetos',
            },
        ),
    ]
