# Generated by Django 6.0.3 on 2026-03-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_expertarticle_projectscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google (Gemini)'), ('anthropic', 'Anthropic (Claude)'), ('xai', 'xAI (Grok)')], max_length=20, verbose_name='Provedor')),
                ('model_name', models.CharField(help_text='Ex: gpt-4.1-mini, gemini-2.5-flash, claude-sonnet-4-20250514', max_length=100, verbose_name='Modelo')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('is_default_text', models.BooleanField(default=False, verbose_name='Padrão para Texto')),
                ('is_default_image', models.BooleanField(default=False, verbose_name='Padrão para Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text='{"text": true, "image": false, "vision": false, "embedding": false}', verbose_name='Capacidades')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Provedor de IA',
                'verbose_name_plural': 'Provedores de IA',
                'ordering': ['project', '-is_default_text', 'provider'],
            },
        ),
    ]
