# Generated by Django 6.0.3 on 2026-03-10 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_aiprovider_redesign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_type', models.CharField(choices=[('view_error', 'Erro em View'), ('api_error', 'Erro de API Externa'), ('audit_error', 'Erro na Auditoria'), ('integration_error', 'Erro de Integração'), ('unknown', 'Desconhecido')], default='unknown', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], default='error', max_length=10)),
                ('error_message', models.TextField(verbose_name='Mensagem')),
                ('traceback', models.TextField(blank=True, verbose_name='Traceback')),
                ('view_name', models.CharField(blank=True, max_length=200, verbose_name='View')),
                ('url_path', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('request_body', models.TextField(blank=True, verbose_name='Request Body (sanitizado)')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('developer_notes', models.TextField(blank=True, verbose_name='Notas do Desenvolvedor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Erro do Sistema',
                'verbose_name_plural': 'Logs de Erros do Sistema',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'resolved'], name='core_system_timesta_d2e782_idx'), models.Index(fields=['error_type', '-timestamp'], name='core_system_error_t_7e3112_idx')],
            },
        ),
    ]
