# Generated by Django 6.0.2 on 2026-02-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('overall_score', models.IntegerField(default=0, verbose_name='Score Geral (0-100)')),
                ('meta_score', models.IntegerField(default=0, verbose_name='Meta Tags Score')),
                ('content_score', models.IntegerField(default=0, verbose_name='Conteúdo Score')),
                ('technical_score', models.IntegerField(default=0, verbose_name='Técnico Score')),
                ('performance_score', models.IntegerField(default=0, verbose_name='Performance Score')),
                ('structured_data_score', models.IntegerField(default=0, verbose_name='Dados Estruturados Score')),
                ('pages_crawled', models.IntegerField(default=0)),
                ('issues_critical', models.IntegerField(default=0)),
                ('issues_warning', models.IntegerField(default=0)),
                ('issues_info', models.IntegerField(default=0)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_audits', to='core.site')),
            ],
            options={
                'verbose_name': 'Auditoria SEO',
                'verbose_name_plural': 'Auditorias SEO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL da Página')),
                ('score', models.IntegerField(default=0, verbose_name='Score (0-100)')),
                ('has_title', models.BooleanField(default=False)),
                ('title_length', models.IntegerField(default=0)),
                ('has_meta_description', models.BooleanField(default=False)),
                ('meta_description_length', models.IntegerField(default=0)),
                ('has_canonical', models.BooleanField(default=False)),
                ('has_og_tags', models.BooleanField(default=False)),
                ('has_h1', models.BooleanField(default=False)),
                ('h1_count', models.IntegerField(default=0)),
                ('h2_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('has_images_alt', models.BooleanField(default=False)),
                ('images_total', models.IntegerField(default=0)),
                ('images_missing_alt', models.IntegerField(default=0)),
                ('has_structured_data', models.BooleanField(default=False)),
                ('structured_data_types', models.JSONField(blank=True, default=list)),
                ('has_robots_meta', models.BooleanField(default=False)),
                ('is_indexable', models.BooleanField(default=True)),
                ('http_status', models.IntegerField(default=200)),
                ('load_time_ms', models.IntegerField(default=0, verbose_name='Tempo de Carregamento (ms)')),
                ('issues', models.JSONField(blank=True, default=list, verbose_name='Problemas')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_scores', to='seo.seoaudit')),
            ],
            options={
                'verbose_name': 'Score de Página',
                'verbose_name_plural': 'Scores de Páginas',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='KeywordTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300, verbose_name='Palavra-chave')),
                ('target_url', models.URLField(blank=True, verbose_name='URL Alvo')),
                ('current_position', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Posição Atual')),
                ('best_position', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Melhor Posição')),
                ('impressions_30d', models.IntegerField(default=0, verbose_name='Impressões 30d')),
                ('clicks_30d', models.IntegerField(default=0, verbose_name='Cliques 30d')),
                ('ctr_30d', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='CTR 30d')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Keyword Prioritária')),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_keywords', to='core.site')),
            ],
            options={
                'verbose_name': 'Keyword Tracking',
                'verbose_name_plural': 'Keywords Tracking',
                'ordering': ['current_position'],
                'unique_together': {('site', 'keyword')},
            },
        ),
    ]
