# Generated by Django 6.0.3 on 2026-03-10 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Sugestão'), ('ux', 'Usabilidade'), ('performance', 'Performance'), ('other', 'Outro')], default='bug', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('page_url', models.URLField(blank=True, max_length=500)),
                ('screenshot', models.ImageField(blank=True, upload_to='feedback/%Y/%m/')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('in_progress', 'Em Análise'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10)),
                ('developer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
