# Generated by Django 6.0.3 on 2026-03-10 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0002_feedbacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklog',
            name='chat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_logs', to='chat_support.chatsession'),
        ),
        migrations.AddField(
            model_name='feedbacklog',
            name='chat_transcript',
            field=models.TextField(blank=True, help_text='Últimas mensagens do chat ao reportar'),
        ),
        migrations.AddField(
            model_name='feedbacklog',
            name='error_context',
            field=models.JSONField(blank=True, default=dict, help_text='Contexto extra do erro (URL, traceback, etc.)'),
        ),
        migrations.AddField(
            model_name='feedbacklog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
