# Generated by Django 6.0.3 on 2026-03-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0003_feedbacklog_chat_session_feedbacklog_chat_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacklog',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('approved', 'Aprovado'), ('in_progress', 'Em Análise'), ('resolved', 'Resolvido'), ('rejected', 'Rejeitado'), ('closed', 'Fechado')], default='new', max_length=20),
        ),
    ]
