# Generated by Django 6.0.3 on 2026-03-11 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0004_add_approved_rejected_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feedback/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat_support.feedbacklog')),
            ],
            options={
                'verbose_name': 'Imagem de Feedback',
                'verbose_name_plural': 'Imagens de Feedback',
                'ordering': ['created_at'],
            },
        ),
    ]
