# Generated by Django 6.0.2 on 2026-02-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('traffic', 'Aquisição de Tráfego'), ('engagement', 'Engajamento'), ('conversions', 'Conversões'), ('pages', 'Páginas')], max_length=20)),
                ('date_start', models.DateField(verbose_name='Data Início')),
                ('date_end', models.DateField(verbose_name='Data Fim')),
                ('data', models.JSONField(default=dict, verbose_name='Dados do Relatório')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_reports', to='core.site')),
            ],
            options={
                'verbose_name': 'Relatório GA4',
                'verbose_name_plural': 'Relatórios GA4',
                'ordering': ['-date_end'],
            },
        ),
        migrations.CreateModel(
            name='GA4EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Evento')),
                ('client_id', models.CharField(max_length=200, verbose_name='Client ID')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parâmetros')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('validated', 'Validado'), ('failed', 'Falhou')], default='sent', max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_event_logs', to='core.site')),
            ],
            options={
                'verbose_name': 'Log de Evento GA4',
                'verbose_name_plural': 'Logs de Eventos GA4',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', '-created_at'], name='analytics_g_site_id_e40a5c_idx'), models.Index(fields=['event_name', '-created_at'], name='analytics_g_event_n_7bd43b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchConsoleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('query', models.CharField(blank=True, max_length=500, verbose_name='Query')),
                ('page', models.URLField(blank=True, verbose_name='Página')),
                ('country', models.CharField(blank=True, default='BRA', max_length=5)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('clicks', models.IntegerField(default=0, verbose_name='Cliques')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impressões')),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='CTR')),
                ('position', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Posição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_data', to='core.site')),
            ],
            options={
                'verbose_name': 'Dados Search Console',
                'verbose_name_plural': 'Dados Search Console',
                'ordering': ['-date', '-clicks'],
                'indexes': [models.Index(fields=['site', '-date'], name='analytics_s_site_id_d995cb_idx'), models.Index(fields=['query'], name='analytics_s_query_ae45d0_idx'), models.Index(fields=['page'], name='analytics_s_page_83506b_idx')],
            },
        ),
    ]
