# Generated by Django 6.0.2 on 2026-03-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_site_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads')], max_length=30, verbose_name='Plataforma')),
                ('name', models.CharField(help_text="Ex: 'Google Ads \u2014 My Face', 'Meta Ads \u2014 Beezle'", max_length=200, verbose_name='Nome do Canal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
                'ordering': ['project', 'platform'],
                'unique_together': {('project', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='ChannelCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, help_text='Formato: 123-456-7890', max_length=30, verbose_name='Customer ID')),
                ('developer_token', models.CharField(blank=True, max_length=100, verbose_name='Developer Token')),
                ('client_id', models.CharField(blank=True, max_length=200, verbose_name='OAuth Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=200, verbose_name='OAuth Client Secret')),
                ('refresh_token', models.CharField(blank=True, max_length=500, verbose_name='OAuth Refresh Token')),
                ('login_customer_id', models.CharField(blank=True, max_length=30, verbose_name='Login Customer ID (MCC)')),
                ('access_token', models.CharField(blank=True, max_length=500, verbose_name='Access Token')),
                ('account_id', models.CharField(blank=True, help_text='Ex: act_123456789', max_length=100, verbose_name='Ad Account ID')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Campos adicionais por plataforma (JSON)', verbose_name='Dados Extras')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='channels.channel', verbose_name='Canal')),
            ],
            options={
                'verbose_name': 'Credencial de Canal',
                'verbose_name_plural': 'Credenciais de Canais',
            },
        ),
    ]
