# Generated by Django 6.0.3 on 2026-03-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PAUSED', 'Pausado'), ('WOULD_PAUSE', 'Pausaria (monitor)'), ('REACTIVATED', 'Reativado'), ('WOULD_REACTIVATE', 'Reativaria (monitor)'), ('SCALED', 'Escalonado'), ('WOULD_SCALE', 'Escalonaria (monitor)'), ('PAUSE_FAILED', 'Falha ao Pausar'), ('REACTIVATE_FAILED', 'Falha ao Reativar'), ('SCALE_FAILED', 'Falha ao Escalonar'), ('BUDGET_LIMIT', 'Limite de Orçamento'), ('SKIPPED', 'Ignorado'), ('NO_DATA', 'Sem Dados')], max_length=20)),
                ('target_type', models.CharField(choices=[('campaign', 'Campanha'), ('ad_set', 'Conjunto de Anúncios'), ('account', 'Conta')], default='ad_set', max_length=10)),
                ('target_id', models.CharField(max_length=100, verbose_name='ID do Alvo')),
                ('target_name', models.CharField(max_length=300, verbose_name='Nome do Alvo')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('mode', models.CharField(default='monitor', max_length=10)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizer_actions', to='channels.channel', verbose_name='Canal')),
            ],
            options={
                'verbose_name': 'Ação do Otimizador',
                'verbose_name_plural': 'Ações do Otimizador',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('mode', models.CharField(choices=[('monitor', 'Monitor (somente leitura)'), ('active', 'Ativo (executa ações)')], default='monitor', max_length=10, verbose_name='Modo')),
                ('optimize_by', models.CharField(choices=[('cpa', 'CPA (Custo por Aquisição)'), ('roas', 'ROAS (Retorno sobre Gasto)')], default='cpa', max_length=5, verbose_name='Otimizar por')),
                ('cpa_max', models.DecimalField(blank=True, decimal_places=2, help_text='Stop loss — pausa se CPA ultrapassar', max_digits=10, null=True, verbose_name='CPA Máximo (R$)')),
                ('roas_min', models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 2.0 = retorno de 2x', max_digits=5, null=True, verbose_name='ROAS Mínimo')),
                ('sale_value', models.DecimalField(blank=True, decimal_places=2, help_text='Para cálculo de ROAS', max_digits=10, null=True, verbose_name='Valor da Venda (R$)')),
                ('pause_behavior', models.CharField(choices=[('rigid', 'Rígido (pausa imediata)'), ('flexible', 'Flexível (aguarda mais dados)')], default='rigid', max_length=10, verbose_name='Comportamento de Pausa')),
                ('scale_behavior', models.CharField(choices=[('conservative', 'Conservador (+20%)'), ('accelerated', 'Acelerado (+50%)')], default='conservative', max_length=15, verbose_name='Comportamento de Escala')),
                ('daily_budget_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Teto Diário por Campanha (R$)')),
                ('monthly_budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Limite Mensal da Conta (R$)')),
                ('lookback_days', models.IntegerField(default=1, verbose_name='Dias de Lookback')),
                ('min_spend_to_evaluate', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Gasto Mínimo para Avaliar (R$)')),
                ('excluded_campaigns', models.JSONField(blank=True, default=list, verbose_name='Campanhas Excluídas (IDs)')),
                ('excluded_ad_sets', models.JSONField(blank=True, default=list, verbose_name='Conjuntos Excluídos (IDs)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optimizer_config', to='channels.channel', verbose_name='Canal')),
            ],
            options={
                'verbose_name': 'Configuração do Otimizador',
                'verbose_name_plural': 'Configurações do Otimizador',
            },
        ),
    ]
